version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-education-network
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
